from __future__ import annotations

THEME_ORDER = [
    "Theme_1_Multidimensional_Wellbeing_Framework",
    "Theme_2_Youth_Social_Ecology_and_Disconnection",
    "Theme_3_Pressured_and_Trust_Sensitive_Care",
    "Theme_4_Youth_Sensitive_Implementation",
]

THEME_LABELS = {
    "Theme_1_Multidimensional_Wellbeing_Framework": (
        "Multidimensional wellbeing as balanced stability, moral-spiritual grounding, and daily functioning"
    ),
    "Theme_2_Youth_Social_Ecology_and_Disconnection": (
        "Youth wellbeing as relational ecology, peer worlds, and social disconnection"
    ),
    "Theme_3_Pressured_and_Trust_Sensitive_Care": (
        "Holistic care constrained by rushed, fragmented, and trust-sensitive encounters"
    ),
    "Theme_4_Youth_Sensitive_Implementation": (
        "Coordinated, youth-sensitive, and institutionally backed routes to change"
    ),
}

THEME_CODES = {
    "Theme_1_Multidimensional_Wellbeing_Framework": {
        "balance_multidimensional",
        "contentment_acceptance",
        "spiritual_moral_anchor",
        "inner_peace_stability",
        "support_as_wellbeing_core",
        "functionality_self_management",
    },
    "Theme_2_Youth_Social_Ecology_and_Disconnection": {
        "family_support_ecology",
        "peer_belonging_isolation",
        "youth_transition_pressure",
        "digital_social_media_pressure",
        "youth_voice_visibility",
        "intergenerational_disconnect",
    },
    "Theme_3_Pressured_and_Trust_Sensitive_Care": {
        "consultation_time_pressure",
        "quantity_over_quality",
        "stigma_help_seeking_barrier",
        "confidentiality_trust_barrier",
        "language_cultural_mismatch",
        "fragmented_service_pathway",
        "access_delay_waiting",
        "environment_design_stress",
        "whole_person_care",
        "empathy_reassurance",
        "patient_provider_relationship",
        "self_disclosure_hidden_distress",
    },
    "Theme_4_Youth_Sensitive_Implementation": {
        "communication_training_need",
        "interdisciplinary_integration",
        "awareness_outreach",
        "youth_specific_service_design",
        "family_inclusive_care",
        "healthcare_worker_wellbeing",
        "environmental_design_improvement",
        "practical_recommendation",
        "top_down_system_change",
    },
}

SELECTED_EXCERPTS = {
    "Theme_1_Multidimensional_Wellbeing_Framework": [
        "D2_S0001",
        "D2_S0011",
        "D2_S0240",
        "D2_S0245",
        "D2_S0255",
        "D2_S0131",
        "D2_S0132",
        "D2_S0175",
    ],
    "Theme_2_Youth_Social_Ecology_and_Disconnection": [
        "D2_S0026",
        "D2_S0028",
        "D2_S0029",
        "D2_S0031",
        "D2_S0033",
        "D2_S0082",
        "D2_S0205",
        "D2_S0298",
    ],
    "Theme_3_Pressured_and_Trust_Sensitive_Care": [
        "D2_S0036",
        "D2_S0046",
        "D2_S0051",
        "D2_S0086",
        "D2_S0089",
        "D2_S0105",
        "D2_S0150",
        "D2_S0151",
        "D2_S0152",
        "D2_S0154",
        "D2_S0236",
        "D2_S0285",
        "D2_S0292",
    ],
    "Theme_4_Youth_Sensitive_Implementation": [
        "D2_S0042",
        "D2_S0104",
        "D2_S0109",
        "D2_S0112",
        "D2_S0302",
        "D2_S0304",
        "D2_S0306",
        "D2_S0309",
        "D2_S0313",
        "D2_S0162",
        "D2_S0166",
        "D2_S0169",
    ],
}

NOTE_TAKER_ROWS = [
    {
        "evidence_id": "D2_E001",
        "theme": "Theme_1_Multidimensional_Wellbeing_Framework",
        "segment_id": "",
        "source_file": "HWYO5NT1.docx",
        "table_id": "5",
        "speaker_code": "",
        "speaker_type": "note_taker_summary",
        "role_label": "Note-taker summary",
        "attribution_status": "note_taker_summary",
        "evidence_type": "note_taker_summary",
        "question_id": "Q1",
        "excerpt_text": "جوهر الحياة الطيبة هو التوازن بين الجوانب الجسدية، النفسية، العقلية، الروحية، والاجتماعية.",
        "codes": "balance_multidimensional",
        "language": "ar",
        "report_use": "contextual_theme_support",
    },
    {
        "evidence_id": "D2_E002",
        "theme": "Theme_2_Youth_Social_Ecology_and_Disconnection",
        "segment_id": "",
        "source_file": "HWYO0NT1.docx",
        "table_id": "0",
        "speaker_code": "",
        "speaker_type": "note_taker_summary",
        "role_label": "Note-taker summary",
        "attribution_status": "note_taker_summary",
        "evidence_type": "note_taker_summary",
        "question_id": "Q3",
        "excerpt_text": "مفهوم العزلة الاجتماعية بالوضع الحالي أنا في نظري هو من أخطر المشاكل التي تواجه المجتمع وتواجه العافية المجتمعية.",
        "codes": "peer_belonging_isolation;digital_social_media_pressure",
        "language": "ar",
        "report_use": "contextual_theme_support",
    },
    {
        "evidence_id": "D2_E003",
        "theme": "Theme_3_Pressured_and_Trust_Sensitive_Care",
        "segment_id": "",
        "source_file": "HWYO4NT1.docx",
        "table_id": "4",
        "speaker_code": "",
        "speaker_type": "note_taker_summary",
        "role_label": "Note-taker summary",
        "attribution_status": "note_taker_summary",
        "evidence_type": "note_taker_summary",
        "question_id": "Q4",
        "excerpt_text": "المواعيد وانتظار الكثير من الوقت للحصول على موعد. وهذا يعتبر تحدي للشباب لأنه يكره الانتظار، مما يسبب عزوف الشباب لزيارة المراكز الصحية.",
        "codes": "access_delay_waiting",
        "language": "ar",
        "report_use": "contextual_theme_support",
    },
    {
        "evidence_id": "D2_E004",
        "theme": "Theme_4_Youth_Sensitive_Implementation",
        "segment_id": "",
        "source_file": "HWYO9NT1[7].docx",
        "table_id": "9",
        "speaker_code": "",
        "speaker_type": "note_taker_summary",
        "role_label": "Note-taker summary",
        "attribution_status": "note_taker_summary",
        "evidence_type": "note_taker_summary",
        "question_id": "Q7",
        "excerpt_text": "Social media can be used through a campaign with explanations on how they can get help, and they can reach out to counselors privately, so they do not feel ashamed.",
        "codes": "awareness_outreach;confidentiality_trust_barrier;practical_recommendation",
        "language": "en",
        "report_use": "contextual_theme_support",
    },
    {
        "evidence_id": "D2_E005",
        "theme": "Theme_4_Youth_Sensitive_Implementation",
        "segment_id": "",
        "source_file": "HWYO9NT1[7].docx",
        "table_id": "9",
        "speaker_code": "",
        "speaker_type": "note_taker_summary",
        "role_label": "Note-taker summary",
        "attribution_status": "note_taker_summary",
        "evidence_type": "note_taker_summary",
        "question_id": "Q6",
        "excerpt_text": "The first assessment tool is being ruled out in school. Parenting the parents by teaching them.",
        "codes": "communication_training_need;family_inclusive_care",
        "language": "en",
        "report_use": "contextual_theme_support",
    },
]

SALIENCE_LABELS = [
    "most_prominent",
    "highly_prominent",
    "moderately_prominent",
    "present_but_less_prominent",
]
